# NumPy Exercises

#### Import NumPy as np

In [1]:
import numpy as np

#### Crear una matriz de 10 ceros

In [2]:
# CODE HERE

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear una matriz con 10 unos

In [4]:
# CODE HERE
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [9]:
# CODE HERE
np.array((5,5,5,5,5),dtype=int)

array([5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [11]:
# CODE HERE
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [12]:
# CODE HERE
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [13]:
np.array([i for i in range (10,50) if i%2 == 0])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
# CODE HERE
arr = np.array((0,1,2,3,4,5,6,7,8))
arr1 =np.ones(shape=(3,3))
arr * arr1

ValueError: operands could not be broadcast together with shapes (9,) (3,3) 

In [20]:
#podes partir del range del vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
#hacer una de unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# multiplicarlas

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [22]:
# CODE HERE
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [23]:
# CODE HERE
np.random.rand()

0.5167580428317508

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [24]:
# CODE HERE
np.random.rand(25)

array([0.71798573, 0.49510454, 0.32653944, 0.98664087, 0.23251405,
       0.44973945, 0.66982835, 0.1313707 , 0.93604043, 0.76875384,
       0.73082907, 0.63211062, 0.1776411 , 0.32603578, 0.68655436,
       0.84861455, 0.63102901, 0.97867602, 0.32080533, 0.12936553,
       0.6788542 , 0.70664279, 0.14640569, 0.12483205, 0.50641981])

#### Create the following matrix:

In [31]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [33]:
np.linspace(0.01,1.01,100).reshape(10,10)

array([[0.01      , 0.02010101, 0.03020202, 0.04030303, 0.05040404,
        0.06050505, 0.07060606, 0.08070707, 0.09080808, 0.10090909],
       [0.1110101 , 0.12111111, 0.13121212, 0.14131313, 0.15141414,
        0.16151515, 0.17161616, 0.18171717, 0.19181818, 0.20191919],
       [0.2120202 , 0.22212121, 0.23222222, 0.24232323, 0.25242424,
        0.26252525, 0.27262626, 0.28272727, 0.29282828, 0.30292929],
       [0.3130303 , 0.32313131, 0.33323232, 0.34333333, 0.35343434,
        0.36353535, 0.37363636, 0.38373737, 0.39383838, 0.40393939],
       [0.4140404 , 0.42414141, 0.43424242, 0.44434343, 0.45444444,
        0.46454545, 0.47464646, 0.48474747, 0.49484848, 0.50494949],
       [0.51505051, 0.52515152, 0.53525253, 0.54535354, 0.55545455,
        0.56555556, 0.57565657, 0.58575758, 0.59585859, 0.6059596 ],
       [0.61606061, 0.62616162, 0.63626263, 0.64636364, 0.65646465,
        0.66656566, 0.67666667, 0.68676768, 0.69686869, 0.7069697 ],
       [0.71707071, 0.72717172, 0.7372727

#### Create an array of 20 linearly spaced points between 0 and 1:

In [38]:
np.linspace(0,1,20).reshape(4,5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

## Numpy Indexing and Selection

Ahora se le darán algunas matrices y se le pedirá que replique los resultados de la matriz resultante:

In [40]:
# HERE IS THE GIVEN MATRIX CALLED MAT
# USE IT FOR THE FOLLOWING TASKS
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
mat[1:,1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
mat[3][4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [44]:
mat[:4,1]

array([ 2,  7, 12, 17])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [47]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
# CODE HERE

In [48]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [ ]:
# CODE HERE

In [49]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
# CODE HERE

In [54]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [53]:
np.sum

array([55, 60, 65, 70, 75])

## Bonus Question

Trabajamos mucho con datos aleatorios con numpy, pero ¿hay alguna manera de asegurarnos de que siempre obtengamos los mismos números aleatorios? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)